### ISSUE TITLE
updated to feature parity with Vapor Auth Demo

### ISSUE THREAD

**Issue by proyb6** [stormpath/Turnstile-Perfect-Example#1]
I see the commits show 
```
updated to feature parity with Vapor Auth Demo
```
should be Perfect Auth Demo?

**Comment by edjiang** [comment]
There's a Vapor example as well, which you can find here:

https://github.com/stormpath/Turnstile-Vapor-Example

Those commits were to update this example to match what I had in the Vapor example.
